/***************************************************************************//**
* File Name: cycfg_gatt_db.h
*
* Description:
* Definitions for constants used in the device's GATT database and function
* prototypes.
* This file should not be modified. It was automatically generated by
* Bluetooth Configurator 3.30.0.3160
*
********************************************************************************
* Copyright 2025 Cypress Semiconductor Corporation (an Infineon company) or
* an affiliate of Cypress Semiconductor Corporation.
* SPDX-License-Identifier: Apache-2.0
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*******************************************************************************/

#if !defined(CYCFG_GATT_DB_H)
#define CYCFG_GATT_DB_H

#include "stdint.h"

#define __UUID_SERVICE_GENERIC_ACCESS                    0x1800
#define __UUID_CHARACTERISTIC_DEVICE_NAME                0x2A00
#define __UUID_CHARACTERISTIC_APPEARANCE                 0x2A01
#define __UUID_SERVICE_GENERIC_ATTRIBUTE                 0x1801
#define __UUID_CHARACTERISTIC_SERVICE_CHANGED            0x2A05
#define __UUID_DESCRIPTOR_CLIENT_CHARACTERISTIC_CONFIGURATION    0x2902
#define __UUID_SERVICE_HELLO_SENSOR_1                    0x10, 0x1D, 0xA4, 0x4A, 0xD6, 0x9E, 0x08, 0xAA, 0xF4, 0x40, 0x12, 0xA2, 0xF5, 0xE2, 0xD0, 0xE9
#define __UUID_CHARACTERISTIC_HELLO_SENSOR_1_NOTIFY      0xB1, 0xAB, 0x23, 0xA3, 0x9C, 0xBE, 0x4B, 0xBC, 0xC3, 0x4F, 0xFE, 0x68, 0xF4, 0xA9, 0xD9, 0x07
#define __UUID_CHARACTERISTIC_HELLO_SENSOR_1_BLINK       0x5A, 0x06, 0xFF, 0x11, 0xD8, 0xBC, 0x79, 0x88, 0x76, 0x49, 0x85, 0x21, 0xB9, 0x3F, 0x39, 0x7C
#define __UUID_CHARACTERISTIC_HELLO_SENSOR_1_DEVICE_NAME    0x1F, 0x66, 0xC4, 0x90, 0x02, 0x78, 0xAF, 0x90, 0x87, 0x4B, 0x6B, 0x0C, 0x49, 0x16, 0x54, 0x82
#define __UUID_SERVICE_HELLO_SENSOR_2                    0xD8, 0xE6, 0xDC, 0x06, 0xD6, 0x5B, 0x6E, 0x8C, 0xC2, 0x40, 0xD6, 0xD5, 0x02, 0x21, 0x66, 0x21
#define __UUID_CHARACTERISTIC_HELLO_SENSOR_2_NOTIFY      0x5F, 0xC3, 0x0B, 0xFD, 0xC1, 0x4F, 0xB6, 0x95, 0xC8, 0x47, 0xE6, 0xDB, 0x3E, 0x7F, 0x92, 0xD2
#define __UUID_CHARACTERISTIC_HELLO_SENSOR_2_BLINK       0x52, 0x30, 0xEA, 0x09, 0x41, 0x6D, 0xD7, 0xB2, 0x58, 0x47, 0xC2, 0xEF, 0x81, 0xB5, 0x57, 0xB6
#define __UUID_CHARACTERISTIC_HELLO_SENSOR_2_DEVICE_NAME    0x05, 0x9A, 0xF8, 0x34, 0xE1, 0x5C, 0x42, 0xB6, 0xDF, 0x45, 0x16, 0xA8, 0xCA, 0xC3, 0x24, 0x47
#define __UUID_SERVICE_HELLO_SENSOR_3                    0xE2, 0x95, 0x9B, 0xAA, 0x70, 0x59, 0xB3, 0xA7, 0x35, 0x45, 0xB8, 0x35, 0x1A, 0x23, 0x5D, 0xAD
#define __UUID_CHARACTERISTIC_HELLO_SENSOR_3_NOTIFY      0xB2, 0xEF, 0x86, 0xE7, 0xC6, 0x64, 0xD9, 0x98, 0x9B, 0x49, 0xEF, 0xAA, 0x07, 0x1F, 0x4E, 0x8F
#define __UUID_CHARACTERISTIC_HELLO_SENSOR_3_BLINK       0xE4, 0xD9, 0x18, 0x23, 0x03, 0x19, 0x6C, 0x9B, 0x88, 0x4B, 0xC4, 0xA4, 0x36, 0x24, 0x4F, 0x42
#define __UUID_CHARACTERISTIC_HELLO_SENSOR_3_DEVICE_NAME    0xB9, 0x62, 0x1F, 0xE4, 0x67, 0x66, 0x0D, 0x81, 0x55, 0x4C, 0x5F, 0x0D, 0x6A, 0xA3, 0x10, 0xE7

/* Service Generic Access */
#define HDLS_GAP                                         0x0001
/* Characteristic Device Name */
#define HDLC_GAP_DEVICE_NAME                             0x0002
#define HDLC_GAP_DEVICE_NAME_VALUE                       0x0003
#define MAX_LEN_GAP_DEVICE_NAME                          0x000C
/* Characteristic Appearance */
#define HDLC_GAP_APPEARANCE                              0x0004
#define HDLC_GAP_APPEARANCE_VALUE                        0x0005
#define MAX_LEN_GAP_APPEARANCE                           0x0002

/* Service Generic Attribute */
#define HDLS_GATT                                        0x0006
/* Characteristic Service Changed */
#define HDLC_GATT_SERVICE_CHANGED                        0x0007
#define HDLC_GATT_SERVICE_CHANGED_VALUE                  0x0008
#define MAX_LEN_GATT_SERVICE_CHANGED                     0x0004
/* Descriptor Client Characteristic Configuration */
#define HDLD_GATT_SERVICE_CHANGED_CLIENT_CHAR_CONFIG     0x0009
#define MAX_LEN_GATT_SERVICE_CHANGED_CLIENT_CHAR_CONFIG    0x0002

/* Service Hello Sensor 1 */
#define HDLS_HELLO_SENSOR_1                              0x000A
/* Characteristic Notify */
#define HDLC_HELLO_SENSOR_1_NOTIFY                       0x000B
#define HDLC_HELLO_SENSOR_1_NOTIFY_VALUE                 0x000C
#define MAX_LEN_HELLO_SENSOR_1_NOTIFY                    0x0007
/* Descriptor Client Characteristic Configuration */
#define HDLD_HELLO_SENSOR_1_NOTIFY_CLIENT_CHAR_CONFIG    0x000D
#define MAX_LEN_HELLO_SENSOR_1_NOTIFY_CLIENT_CHAR_CONFIG    0x0002
/* Characteristic Blink */
#define HDLC_HELLO_SENSOR_1_BLINK                        0x000E
#define HDLC_HELLO_SENSOR_1_BLINK_VALUE                  0x000F
#define MAX_LEN_HELLO_SENSOR_1_BLINK                     0x0001
/* Characteristic Device name */
#define HDLC_HELLO_SENSOR_1_DEVICE_NAME                  0x0010
#define HDLC_HELLO_SENSOR_1_DEVICE_NAME_VALUE            0x0011
#define MAX_LEN_HELLO_SENSOR_1_DEVICE_NAME               0x0014

/* Service Hello Sensor 2 */
#define HDLS_HELLO_SENSOR_2                              0x0012
/* Characteristic Notify */
#define HDLC_HELLO_SENSOR_2_NOTIFY                       0x0013
#define HDLC_HELLO_SENSOR_2_NOTIFY_VALUE                 0x0014
#define MAX_LEN_HELLO_SENSOR_2_NOTIFY                    0x0007
/* Descriptor Client Characteristic Configuration */
#define HDLD_HELLO_SENSOR_2_NOTIFY_CLIENT_CHAR_CONFIG    0x0015
#define MAX_LEN_HELLO_SENSOR_2_NOTIFY_CLIENT_CHAR_CONFIG    0x0002
/* Characteristic Blink */
#define HDLC_HELLO_SENSOR_2_BLINK                        0x0016
#define HDLC_HELLO_SENSOR_2_BLINK_VALUE                  0x0017
#define MAX_LEN_HELLO_SENSOR_2_BLINK                     0x0001
/* Characteristic Device Name */
#define HDLC_HELLO_SENSOR_2_DEVICE_NAME                  0x0018
#define HDLC_HELLO_SENSOR_2_DEVICE_NAME_VALUE            0x0019
#define MAX_LEN_HELLO_SENSOR_2_DEVICE_NAME               0x0014

/* Service Hello Sensor 3 */
#define HDLS_HELLO_SENSOR_3                              0x001A
/* Characteristic Notify */
#define HDLC_HELLO_SENSOR_3_NOTIFY                       0x001B
#define HDLC_HELLO_SENSOR_3_NOTIFY_VALUE                 0x001C
#define MAX_LEN_HELLO_SENSOR_3_NOTIFY                    0x0007
/* Descriptor Client Characteristic Configuration */
#define HDLD_HELLO_SENSOR_3_NOTIFY_CLIENT_CHAR_CONFIG    0x001D
#define MAX_LEN_HELLO_SENSOR_3_NOTIFY_CLIENT_CHAR_CONFIG    0x0002
/* Characteristic Blink */
#define HDLC_HELLO_SENSOR_3_BLINK                        0x001E
#define HDLC_HELLO_SENSOR_3_BLINK_VALUE                  0x001F
#define MAX_LEN_HELLO_SENSOR_3_BLINK                     0x0001
/* Characteristic Device Name */
#define HDLC_HELLO_SENSOR_3_DEVICE_NAME                  0x0020
#define HDLC_HELLO_SENSOR_3_DEVICE_NAME_VALUE            0x0021
#define MAX_LEN_HELLO_SENSOR_3_DEVICE_NAME               0x0014


/* External Lookup Table Entry */
typedef struct
{
    uint16_t handle;
    uint16_t max_len;
    uint16_t cur_len;
    uint8_t  *p_data;
} gatt_db_lookup_table_t;

/* External definitions */
extern const uint8_t  gatt_database[];
extern const uint16_t gatt_database_len;
extern gatt_db_lookup_table_t app_gatt_db_ext_attr_tbl[];
extern const uint16_t app_gatt_db_ext_attr_tbl_size;
extern uint8_t app_gap_device_name[];
extern const uint16_t app_gap_device_name_len;
extern uint8_t app_gap_appearance[];
extern const uint16_t app_gap_appearance_len;
extern uint8_t app_gatt_service_changed[];
extern const uint16_t app_gatt_service_changed_len;
extern uint8_t app_gatt_service_changed_client_char_config[];
extern const uint16_t app_gatt_service_changed_client_char_config_len;
extern uint8_t app_hello_sensor_1_notify[];
extern const uint16_t app_hello_sensor_1_notify_len;
extern uint8_t app_hello_sensor_1_notify_client_char_config[];
extern const uint16_t app_hello_sensor_1_notify_client_char_config_len;
extern uint8_t app_hello_sensor_1_blink[];
extern const uint16_t app_hello_sensor_1_blink_len;
extern uint8_t app_hello_sensor_1_device_name[];
extern const uint16_t app_hello_sensor_1_device_name_len;
extern uint8_t app_hello_sensor_2_notify[];
extern const uint16_t app_hello_sensor_2_notify_len;
extern uint8_t app_hello_sensor_2_notify_client_char_config[];
extern const uint16_t app_hello_sensor_2_notify_client_char_config_len;
extern uint8_t app_hello_sensor_2_blink[];
extern const uint16_t app_hello_sensor_2_blink_len;
extern uint8_t app_hello_sensor_2_device_name[];
extern const uint16_t app_hello_sensor_2_device_name_len;
extern uint8_t app_hello_sensor_3_notify[];
extern const uint16_t app_hello_sensor_3_notify_len;
extern uint8_t app_hello_sensor_3_notify_client_char_config[];
extern const uint16_t app_hello_sensor_3_notify_client_char_config_len;
extern uint8_t app_hello_sensor_3_blink[];
extern const uint16_t app_hello_sensor_3_blink_len;
extern uint8_t app_hello_sensor_3_device_name[];
extern const uint16_t app_hello_sensor_3_device_name_len;

#endif /* CYCFG_GATT_DB_H */
