#
# This file is generated by ModusToolbox during the 'make getlibs' operation
# Any edits to this file will be lost the next time the library manager is run or
# the next time 'make getlibs' is run.
#
# List of local libraries


# Path to the current BSP
SEARCH_TARGET_APP_CYW955513EVK-01=bsps/TARGET_APP_CYW955513EVK-01

# The search paths for the included middleware
SEARCH_abstraction-rtos=../mtb_shared/abstraction-rtos/release-v1.8.1
SEARCH_btsdk-common=../mtb_shared/wiced_btsdk/dev-kit/libraries/btsdk-common/release-v4.7.0
SEARCH_btsdk-drivers=../mtb_shared/wiced_btsdk/dev-kit/libraries/btsdk-drivers/release-v4.8.0
SEARCH_btsdk-include=../mtb_shared/wiced_btsdk/dev-kit/btsdk-include/release-v4.9.3
SEARCH_retarget-io=../mtb_shared/retarget-io/release-v1.5.0
SEARCH_clib-support=../mtb_shared/clib-support/release-v1.6.0
SEARCH_cmsis=../mtb_shared/cmsis/release-v5.8.0
SEARCH_core-lib=../mtb_shared/core-lib/release-v1.4.4
SEARCH_core-make=../mtb_shared/core-make/release-v3.6.2
SEARCH_mtb-hal-cat5=../mtb_shared/mtb-hal-cat5/release-v1.2.0
SEARCH_mtb-pdl-cat5=../mtb_shared/mtb-pdl-cat5/release-v2.2.0
SEARCH_recipe-make-cat5=../mtb_shared/recipe-make-cat5/release-v1.5.0

# Search libraries added to build
SEARCH_MTB_MK+=$(SEARCH_abstraction-rtos)
SEARCH_MTB_MK+=$(SEARCH_btsdk-common)
SEARCH_MTB_MK+=$(SEARCH_btsdk-drivers)
SEARCH_MTB_MK+=$(SEARCH_btsdk-include)
SEARCH_MTB_MK+=$(SEARCH_retarget-io)
SEARCH_MTB_MK+=$(SEARCH_clib-support)
SEARCH_MTB_MK+=$(SEARCH_cmsis)
SEARCH_MTB_MK+=$(SEARCH_core-lib)
SEARCH_MTB_MK+=$(SEARCH_core-make)
SEARCH_MTB_MK+=$(SEARCH_mtb-hal-cat5)
SEARCH_MTB_MK+=$(SEARCH_mtb-pdl-cat5)
SEARCH_MTB_MK+=$(SEARCH_recipe-make-cat5)

-include $(CY_INTERNAL_APP_PATH)/importedbsp.mk
COMPONENTS += MW_ABSTRACTION_RTOS
COMPONENTS += MW_BTSDK_COMMON
COMPONENTS += MW_BTSDK_DRIVERS
COMPONENTS += MW_BTSDK_INCLUDE
COMPONENTS += MW_RETARGET_IO
COMPONENTS += MW_CLIB_SUPPORT
COMPONENTS += MW_CMSIS
COMPONENTS += MW_CORE_LIB
COMPONENTS += MW_CORE_MAKE
COMPONENTS += MW_MTB_HAL_CAT5
COMPONENTS += MW_MTB_PDL_CAT5
COMPONENTS += MW_RECIPE_MAKE_CAT5


#
# generate make targets for the graphical editors that are specific to this project
#

modlibs:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name library-manager
.PHONY: modlibs

CY_HELP_modlibs=Launches the Library Manager 2.40 GUI
CY_HELP_modlibs_VERBOSE=Launches the Library Manager 2.40 GUI. Check the Library Manager 2.40 User Guide for more information.
mtb_help_tool_modlibs:
	@:
	$(info $(MTB__SPACE)modlibs             $(CY_HELP_modlibs))

mtb_help_tools_end: mtb_help_tool_modlibs
mtb_help_tool_modlibs: mtb_help_tools_start
.PHONY: mtb_help_tool_modlibs

library-manager:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name library-manager
.PHONY: library-manager

CY_HELP_library-manager=Launches the Library Manager 2.40 GUI
CY_HELP_library-manager_VERBOSE=Launches the Library Manager 2.40 GUI. Check the Library Manager 2.40 User Guide for more information.
mtb_help_tool_library-manager:
	@:
	$(info $(MTB__SPACE)library-manager     $(CY_HELP_library-manager))

mtb_help_tools_end: mtb_help_tool_library-manager
mtb_help_tool_library-manager: mtb_help_tools_start
.PHONY: mtb_help_tool_library-manager

bsp-assistant:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name bsp-assistant
.PHONY: bsp-assistant

CY_HELP_bsp-assistant=Launches the BSP Assistant 1.40 GUI
CY_HELP_bsp-assistant_VERBOSE=Launches the BSP Assistant 1.40 GUI. Check the BSP Assistant 1.40 User Guide for more information.
mtb_help_tool_bsp-assistant:
	@:
	$(info $(MTB__SPACE)bsp-assistant       $(CY_HELP_bsp-assistant))

mtb_help_tools_end: mtb_help_tool_bsp-assistant
mtb_help_tool_bsp-assistant: mtb_help_tools_start
.PHONY: mtb_help_tool_bsp-assistant

config_bt:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name bt-configurator
.PHONY: config_bt

CY_HELP_config_bt=Launches the Bluetooth® Configurator 3.30 GUI for the target's cybt file
CY_HELP_config_bt_VERBOSE=Launches the Bluetooth® Configurator 3.30 GUI. Check the Bluetooth® Configurator 3.30 User Guide for more information.
mtb_help_tool_config_bt:
	@:
	$(info $(MTB__SPACE)config_bt           $(CY_HELP_config_bt))

mtb_help_tools_end: mtb_help_tool_config_bt
mtb_help_tool_config_bt: mtb_help_tools_start
.PHONY: mtb_help_tool_config_bt

bt-configurator:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name bt-configurator
.PHONY: bt-configurator

CY_HELP_bt-configurator=Launches the Bluetooth® Configurator 3.30 GUI for the target's cybt file
CY_HELP_bt-configurator_VERBOSE=Launches the Bluetooth® Configurator 3.30 GUI. Check the Bluetooth® Configurator 3.30 User Guide for more information.
mtb_help_tool_bt-configurator:
	@:
	$(info $(MTB__SPACE)bt-configurator     $(CY_HELP_bt-configurator))

mtb_help_tools_end: mtb_help_tool_bt-configurator
mtb_help_tool_bt-configurator: mtb_help_tools_start
.PHONY: mtb_help_tool_bt-configurator

config:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name device-configurator
.PHONY: config

CY_HELP_config=Launches the Device Configurator 5.30 GUI for the target's modus file
CY_HELP_config_VERBOSE=Launches the Device Configurator 5.30 GUI. Check the Device Configurator 5.30 User Guide for more information.
mtb_help_tool_config:
	@:
	$(info $(MTB__SPACE)config              $(CY_HELP_config))

mtb_help_tools_end: mtb_help_tool_config
mtb_help_tool_config: mtb_help_tools_start
.PHONY: mtb_help_tool_config

device-configurator:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name device-configurator
.PHONY: device-configurator

CY_HELP_device-configurator=Launches the Device Configurator 5.30 GUI for the target's modus file
CY_HELP_device-configurator_VERBOSE=Launches the Device Configurator 5.30 GUI. Check the Device Configurator 5.30 User Guide for more information.
mtb_help_tool_device-configurator:
	@:
	$(info $(MTB__SPACE)device-configurator $(CY_HELP_device-configurator))

mtb_help_tools_end: mtb_help_tool_device-configurator
mtb_help_tool_device-configurator: mtb_help_tools_start
.PHONY: mtb_help_tool_device-configurator

.PHONY: mtb_help_tools_start mtb_help_tools_end
